### ISSUE TITLE
License

### ISSUE THREAD

**Issue by g0t4** [andrewpuch/consul_demo#1]
Hi Andrew, can you add a license for this repo? I want to share the scripts you have here, I'm happy to link to your repo.

**Comment by andrewpuch** [comment]
I will get that for you asap!

**Comment by g0t4** [comment]
Thanks Andrew, much appreciated.

Have you used these in prod scenarios?

I'm thinking these are great but if one doesn't keep their scale high
enough to handle peak load these HCs might take down nodes in lieu of just
overwhelming them. I guess either way it's nice to start getting the
warnings to do something about it.

**Comment by andrewpuch** [comment]
I have not used them in prod but just wanted to show how to get a simple setup working :)

**Comment by g0t4** [comment]
Fantastic either way, I'll be incorporating these into a course I'm
creating for Pluralsight.

I made a few modifications I can share if you'd like
- Using MemAvailable from /proc/meminfo
- and the 'id' cpu output from top, I think this might be "new" so might
  not be as backward compat

Thanks for the inspiration here, cool idea to rotate a node out of the pool
if we accidentally overwhelm it, and obviously it should quickly recover.

**Comment by andrewpuch** [comment]
Very cool thanks for that! Are you in NYC? Do you do a lot of tutorials yourself?

**Comment by g0t4** [comment]
Yes I'm in NYC, and yes I love making courses and tutorials. How about you?

**Comment by andrewpuch** [comment]
Nice! I'm in Norwalk CT

**Comment by andrewpuch** [comment]
About an hour train to GCT

**Comment by andrewpuch** [comment]
Complete!

**Comment by g0t4** [comment]
Thanks Andrew
